// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqswsdqyngaylljndahp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxc3dzZHF5bmdheWxsam5kYWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjUxMDIsImV4cCI6MjA2NjA0MTEwMn0.gMZRuoctCUkAulX5-9oK_JmHDOok2wKYqyB_293Tgq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);